spring.application.name=airun-ingestion
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties[spring.json.add.type.headers]=false

airun.ingestion.directory=${AIRUN_INGESTION_DIRECTORY:./trainings}
airun.ingestion.poll-interval=${AIRUN_INGESTION_POLL_INTERVAL:5s}
airun.kafka.raw-activity-topic=${AIRUN_RAW_ACTIVITY_TOPIC:airun.activity.raw.v1}
