CREATE TABLE training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL UNIQUE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    elapsed_time_millis BIGINT NOT NULL,
    distance_meters DOUBLE PRECISION NOT NULL
);

CREATE TABLE training_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id BIGINT NOT NULL REFERENCES training(id) ON DELETE CASCADE,
    session_index INTEGER NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sport VARCHAR(64) NOT NULL,
    elapsed_time_millis BIGINT NOT NULL,
    distance_meters DOUBLE PRECISION NOT NULL,
    average_heart_rate INTEGER,
    maximum_heart_rate INTEGER,
    UNIQUE (training_id, session_index)
);

CREATE TABLE training_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES training_session(id) ON DELETE CASCADE,
    sample_index INTEGER NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    heart_rate INTEGER,
    distance_meters DOUBLE PRECISION,
    speed_meters_per_second DOUBLE PRECISION,
    UNIQUE (session_id, sample_index)
);

CREATE INDEX training_started_at_idx ON training (started_at);
CREATE INDEX training_session_training_id_idx ON training_session (training_id);
CREATE INDEX training_sample_session_id_idx ON training_sample (session_id);
