spring.application.name=airun-activities
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airun}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:airun}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:airun}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:airun-activities}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties[spring.json.value.default.type]=com.mc4.airun.activities.events.RawActivity
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.mc4.airun.activities.events
spring.kafka.consumer.properties[spring.json.use.type.headers]=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties[spring.json.add.type.headers]=false

airun.kafka.raw-activity-topic=${AIRUN_RAW_ACTIVITY_TOPIC:airun.activity.raw.v1}
airun.kafka.activity-stored-topic=${AIRUN_ACTIVITY_STORED_TOPIC:airun.activity.stored.v1}
